//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClientAsmx.ProductServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        private decimal CostField;
        
        private decimal PriceField;
        
        private System.DateTime CreationDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceRef.ProductServiceSoap")]
    public interface ProductServiceSoap {
        
        // CODEGEN: Generating message contract since element name product from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        WpfClientAsmx.ProductServiceRef.AddResponse Add(WpfClientAsmx.ProductServiceRef.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfClientAsmx.ProductServiceRef.AddResponse> AddAsync(WpfClientAsmx.ProductServiceRef.AddRequest request);
        
        // CODEGEN: Generating message contract since element name newProduct from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        WpfClientAsmx.ProductServiceRef.UpdateResponse Update(WpfClientAsmx.ProductServiceRef.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfClientAsmx.ProductServiceRef.UpdateResponse> UpdateAsync(WpfClientAsmx.ProductServiceRef.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        // CODEGEN: Generating message contract since element name GetResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        WpfClientAsmx.ProductServiceRef.GetResponse Get(WpfClientAsmx.ProductServiceRef.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfClientAsmx.ProductServiceRef.GetResponse> GetAsync(WpfClientAsmx.ProductServiceRef.GetRequest request);
        
        // CODEGEN: Generating message contract since element name ListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        WpfClientAsmx.ProductServiceRef.ListResponse List(WpfClientAsmx.ProductServiceRef.ListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfClientAsmx.ProductServiceRef.ListResponse> ListAsync(WpfClientAsmx.ProductServiceRef.ListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public WpfClientAsmx.ProductServiceRef.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(WpfClientAsmx.ProductServiceRef.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfClientAsmx.ProductServiceRef.Product product;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(WpfClientAsmx.ProductServiceRef.Product product) {
            this.product = product;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfClientAsmx.ProductServiceRef.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(WpfClientAsmx.ProductServiceRef.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddResponseBody {
        
        public AddResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public WpfClientAsmx.ProductServiceRef.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(WpfClientAsmx.ProductServiceRef.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WpfClientAsmx.ProductServiceRef.Product newProduct;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(int id, WpfClientAsmx.ProductServiceRef.Product newProduct) {
            this.id = id;
            this.newProduct = newProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfClientAsmx.ProductServiceRef.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(WpfClientAsmx.ProductServiceRef.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public WpfClientAsmx.ProductServiceRef.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(WpfClientAsmx.ProductServiceRef.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfClientAsmx.ProductServiceRef.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(WpfClientAsmx.ProductServiceRef.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfClientAsmx.ProductServiceRef.Product GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(WpfClientAsmx.ProductServiceRef.Product GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="List", Namespace="http://tempuri.org/", Order=0)]
        public WpfClientAsmx.ProductServiceRef.ListRequestBody Body;
        
        public ListRequest() {
        }
        
        public ListRequest(WpfClientAsmx.ProductServiceRef.ListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListRequestBody {
        
        public ListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfClientAsmx.ProductServiceRef.ListResponseBody Body;
        
        public ListResponse() {
        }
        
        public ListResponse(WpfClientAsmx.ProductServiceRef.ListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfClientAsmx.ProductServiceRef.Product[] ListResult;
        
        public ListResponseBody() {
        }
        
        public ListResponseBody(WpfClientAsmx.ProductServiceRef.Product[] ListResult) {
            this.ListResult = ListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductServiceSoapChannel : WpfClientAsmx.ProductServiceRef.ProductServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceSoapClient : System.ServiceModel.ClientBase<WpfClientAsmx.ProductServiceRef.ProductServiceSoap>, WpfClientAsmx.ProductServiceRef.ProductServiceSoap {
        
        public ProductServiceSoapClient() {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfClientAsmx.ProductServiceRef.AddResponse WpfClientAsmx.ProductServiceRef.ProductServiceSoap.Add(WpfClientAsmx.ProductServiceRef.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(WpfClientAsmx.ProductServiceRef.Product product) {
            WpfClientAsmx.ProductServiceRef.AddRequest inValue = new WpfClientAsmx.ProductServiceRef.AddRequest();
            inValue.Body = new WpfClientAsmx.ProductServiceRef.AddRequestBody();
            inValue.Body.product = product;
            WpfClientAsmx.ProductServiceRef.AddResponse retVal = ((WpfClientAsmx.ProductServiceRef.ProductServiceSoap)(this)).Add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfClientAsmx.ProductServiceRef.AddResponse> WpfClientAsmx.ProductServiceRef.ProductServiceSoap.AddAsync(WpfClientAsmx.ProductServiceRef.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfClientAsmx.ProductServiceRef.AddResponse> AddAsync(WpfClientAsmx.ProductServiceRef.Product product) {
            WpfClientAsmx.ProductServiceRef.AddRequest inValue = new WpfClientAsmx.ProductServiceRef.AddRequest();
            inValue.Body = new WpfClientAsmx.ProductServiceRef.AddRequestBody();
            inValue.Body.product = product;
            return ((WpfClientAsmx.ProductServiceRef.ProductServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfClientAsmx.ProductServiceRef.UpdateResponse WpfClientAsmx.ProductServiceRef.ProductServiceSoap.Update(WpfClientAsmx.ProductServiceRef.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(int id, WpfClientAsmx.ProductServiceRef.Product newProduct) {
            WpfClientAsmx.ProductServiceRef.UpdateRequest inValue = new WpfClientAsmx.ProductServiceRef.UpdateRequest();
            inValue.Body = new WpfClientAsmx.ProductServiceRef.UpdateRequestBody();
            inValue.Body.id = id;
            inValue.Body.newProduct = newProduct;
            WpfClientAsmx.ProductServiceRef.UpdateResponse retVal = ((WpfClientAsmx.ProductServiceRef.ProductServiceSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfClientAsmx.ProductServiceRef.UpdateResponse> WpfClientAsmx.ProductServiceRef.ProductServiceSoap.UpdateAsync(WpfClientAsmx.ProductServiceRef.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfClientAsmx.ProductServiceRef.UpdateResponse> UpdateAsync(int id, WpfClientAsmx.ProductServiceRef.Product newProduct) {
            WpfClientAsmx.ProductServiceRef.UpdateRequest inValue = new WpfClientAsmx.ProductServiceRef.UpdateRequest();
            inValue.Body = new WpfClientAsmx.ProductServiceRef.UpdateRequestBody();
            inValue.Body.id = id;
            inValue.Body.newProduct = newProduct;
            return ((WpfClientAsmx.ProductServiceRef.ProductServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfClientAsmx.ProductServiceRef.GetResponse WpfClientAsmx.ProductServiceRef.ProductServiceSoap.Get(WpfClientAsmx.ProductServiceRef.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public WpfClientAsmx.ProductServiceRef.Product Get(int id) {
            WpfClientAsmx.ProductServiceRef.GetRequest inValue = new WpfClientAsmx.ProductServiceRef.GetRequest();
            inValue.Body = new WpfClientAsmx.ProductServiceRef.GetRequestBody();
            inValue.Body.id = id;
            WpfClientAsmx.ProductServiceRef.GetResponse retVal = ((WpfClientAsmx.ProductServiceRef.ProductServiceSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfClientAsmx.ProductServiceRef.GetResponse> WpfClientAsmx.ProductServiceRef.ProductServiceSoap.GetAsync(WpfClientAsmx.ProductServiceRef.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfClientAsmx.ProductServiceRef.GetResponse> GetAsync(int id) {
            WpfClientAsmx.ProductServiceRef.GetRequest inValue = new WpfClientAsmx.ProductServiceRef.GetRequest();
            inValue.Body = new WpfClientAsmx.ProductServiceRef.GetRequestBody();
            inValue.Body.id = id;
            return ((WpfClientAsmx.ProductServiceRef.ProductServiceSoap)(this)).GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfClientAsmx.ProductServiceRef.ListResponse WpfClientAsmx.ProductServiceRef.ProductServiceSoap.List(WpfClientAsmx.ProductServiceRef.ListRequest request) {
            return base.Channel.List(request);
        }
        
        public WpfClientAsmx.ProductServiceRef.Product[] List() {
            WpfClientAsmx.ProductServiceRef.ListRequest inValue = new WpfClientAsmx.ProductServiceRef.ListRequest();
            inValue.Body = new WpfClientAsmx.ProductServiceRef.ListRequestBody();
            WpfClientAsmx.ProductServiceRef.ListResponse retVal = ((WpfClientAsmx.ProductServiceRef.ProductServiceSoap)(this)).List(inValue);
            return retVal.Body.ListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfClientAsmx.ProductServiceRef.ListResponse> WpfClientAsmx.ProductServiceRef.ProductServiceSoap.ListAsync(WpfClientAsmx.ProductServiceRef.ListRequest request) {
            return base.Channel.ListAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfClientAsmx.ProductServiceRef.ListResponse> ListAsync() {
            WpfClientAsmx.ProductServiceRef.ListRequest inValue = new WpfClientAsmx.ProductServiceRef.ListRequest();
            inValue.Body = new WpfClientAsmx.ProductServiceRef.ListRequestBody();
            return ((WpfClientAsmx.ProductServiceRef.ProductServiceSoap)(this)).ListAsync(inValue);
        }
    }
}
