//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.WheatherService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WheatherService.WeatherSoap")]
    public interface WeatherSoap {
        
        // CODEGEN: Generating message contract since element name sLocation from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeather", ReplyAction="*")]
        ConsoleApp1.WheatherService.GetWeatherResponse GetWeather(ConsoleApp1.WheatherService.GetWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeather", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetWeatherResponse> GetWeatherAsync(ConsoleApp1.WheatherService.GetWeatherRequest request);
        
        // CODEGEN: Generating message contract since element name sLocation from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentWeatherConditions", ReplyAction="*")]
        ConsoleApp1.WheatherService.GetCurrentWeatherConditionsResponse GetCurrentWeatherConditions(ConsoleApp1.WheatherService.GetCurrentWeatherConditionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentWeatherConditions", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetCurrentWeatherConditionsResponse> GetCurrentWeatherConditionsAsync(ConsoleApp1.WheatherService.GetCurrentWeatherConditionsRequest request);
        
        // CODEGEN: Generating message contract since element name sLocation from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentWeatherConditionsImageTemp", ReplyAction="*")]
        ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempResponse GetCurrentWeatherConditionsImageTemp(ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentWeatherConditionsImageTemp", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempResponse> GetCurrentWeatherConditionsImageTempAsync(ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempRequest request);
        
        // CODEGEN: Generating message contract since element name _location from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTides", ReplyAction="*")]
        ConsoleApp1.WheatherService.GetTidesResponse GetTides(ConsoleApp1.WheatherService.GetTidesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTides", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetTidesResponse> GetTidesAsync(ConsoleApp1.WheatherService.GetTidesRequest request);
        
        // CODEGEN: Generating message contract since element name _location from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMarineWeather", ReplyAction="*")]
        ConsoleApp1.WheatherService.GetMarineWeatherResponse GetMarineWeather(ConsoleApp1.WheatherService.GetMarineWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMarineWeather", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetMarineWeatherResponse> GetMarineWeatherAsync(ConsoleApp1.WheatherService.GetMarineWeatherRequest request);
        
        // CODEGEN: Generating message contract since element name BodyOfWater from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLures", ReplyAction="*")]
        ConsoleApp1.WheatherService.GetLuresResponse GetLures(ConsoleApp1.WheatherService.GetLuresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLures", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetLuresResponse> GetLuresAsync(ConsoleApp1.WheatherService.GetLuresRequest request);
        
        // CODEGEN: Generating message contract since element name _location from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSST", ReplyAction="*")]
        ConsoleApp1.WheatherService.GetSSTResponse GetSST(ConsoleApp1.WheatherService.GetSSTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSST", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetSSTResponse> GetSSTAsync(ConsoleApp1.WheatherService.GetSSTRequest request);
        
        // CODEGEN: Generating message contract since element name _location from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSSTCharts", ReplyAction="*")]
        ConsoleApp1.WheatherService.GetSSTChartsResponse GetSSTCharts(ConsoleApp1.WheatherService.GetSSTChartsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSSTCharts", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetSSTChartsResponse> GetSSTChartsAsync(ConsoleApp1.WheatherService.GetSSTChartsRequest request);
        
        // CODEGEN: Generating message contract since element name GetMoonPhaseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMoonPhase", ReplyAction="*")]
        ConsoleApp1.WheatherService.GetMoonPhaseResponse GetMoonPhase(ConsoleApp1.WheatherService.GetMoonPhaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMoonPhase", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetMoonPhaseResponse> GetMoonPhaseAsync(ConsoleApp1.WheatherService.GetMoonPhaseRequest request);
        
        // CODEGEN: Generating message contract since element name sLocation from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGamePrediction", ReplyAction="*")]
        ConsoleApp1.WheatherService.GetGamePredictionResponse GetGamePrediction(ConsoleApp1.WheatherService.GetGamePredictionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGamePrediction", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetGamePredictionResponse> GetGamePredictionAsync(ConsoleApp1.WheatherService.GetGamePredictionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeather", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetWeatherRequestBody Body;
        
        public GetWeatherRequest() {
        }
        
        public GetWeatherRequest(ConsoleApp1.WheatherService.GetWeatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeatherRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sLat;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sLong;
        
        public GetWeatherRequestBody() {
        }
        
        public GetWeatherRequestBody(string sLocation, string sLat, string sLong) {
            this.sLocation = sLocation;
            this.sLat = sLat;
            this.sLong = sLong;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeatherResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetWeatherResponseBody Body;
        
        public GetWeatherResponse() {
        }
        
        public GetWeatherResponse(ConsoleApp1.WheatherService.GetWeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWeatherResult;
        
        public GetWeatherResponseBody() {
        }
        
        public GetWeatherResponseBody(string GetWeatherResult) {
            this.GetWeatherResult = GetWeatherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentWeatherConditionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentWeatherConditions", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetCurrentWeatherConditionsRequestBody Body;
        
        public GetCurrentWeatherConditionsRequest() {
        }
        
        public GetCurrentWeatherConditionsRequest(ConsoleApp1.WheatherService.GetCurrentWeatherConditionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentWeatherConditionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sLat;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sLong;
        
        public GetCurrentWeatherConditionsRequestBody() {
        }
        
        public GetCurrentWeatherConditionsRequestBody(string sLocation, string sLat, string sLong) {
            this.sLocation = sLocation;
            this.sLat = sLat;
            this.sLong = sLong;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentWeatherConditionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentWeatherConditionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetCurrentWeatherConditionsResponseBody Body;
        
        public GetCurrentWeatherConditionsResponse() {
        }
        
        public GetCurrentWeatherConditionsResponse(ConsoleApp1.WheatherService.GetCurrentWeatherConditionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentWeatherConditionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentWeatherConditionsResult;
        
        public GetCurrentWeatherConditionsResponseBody() {
        }
        
        public GetCurrentWeatherConditionsResponseBody(string GetCurrentWeatherConditionsResult) {
            this.GetCurrentWeatherConditionsResult = GetCurrentWeatherConditionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentWeatherConditionsImageTempRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentWeatherConditionsImageTemp", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempRequestBody Body;
        
        public GetCurrentWeatherConditionsImageTempRequest() {
        }
        
        public GetCurrentWeatherConditionsImageTempRequest(ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentWeatherConditionsImageTempRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sLat;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sLong;
        
        public GetCurrentWeatherConditionsImageTempRequestBody() {
        }
        
        public GetCurrentWeatherConditionsImageTempRequestBody(string sLocation, string sLat, string sLong) {
            this.sLocation = sLocation;
            this.sLat = sLat;
            this.sLong = sLong;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentWeatherConditionsImageTempResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentWeatherConditionsImageTempResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempResponseBody Body;
        
        public GetCurrentWeatherConditionsImageTempResponse() {
        }
        
        public GetCurrentWeatherConditionsImageTempResponse(ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentWeatherConditionsImageTempResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentWeatherConditionsImageTempResult;
        
        public GetCurrentWeatherConditionsImageTempResponseBody() {
        }
        
        public GetCurrentWeatherConditionsImageTempResponseBody(string GetCurrentWeatherConditionsImageTempResult) {
            this.GetCurrentWeatherConditionsImageTempResult = GetCurrentWeatherConditionsImageTempResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTidesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTides", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetTidesRequestBody Body;
        
        public GetTidesRequest() {
        }
        
        public GetTidesRequest(ConsoleApp1.WheatherService.GetTidesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTidesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _location;
        
        public GetTidesRequestBody() {
        }
        
        public GetTidesRequestBody(string _location) {
            this._location = _location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTidesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTidesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetTidesResponseBody Body;
        
        public GetTidesResponse() {
        }
        
        public GetTidesResponse(ConsoleApp1.WheatherService.GetTidesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTidesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTidesResult;
        
        public GetTidesResponseBody() {
        }
        
        public GetTidesResponseBody(string GetTidesResult) {
            this.GetTidesResult = GetTidesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMarineWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMarineWeather", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetMarineWeatherRequestBody Body;
        
        public GetMarineWeatherRequest() {
        }
        
        public GetMarineWeatherRequest(ConsoleApp1.WheatherService.GetMarineWeatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMarineWeatherRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _location;
        
        public GetMarineWeatherRequestBody() {
        }
        
        public GetMarineWeatherRequestBody(string _location) {
            this._location = _location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMarineWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMarineWeatherResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetMarineWeatherResponseBody Body;
        
        public GetMarineWeatherResponse() {
        }
        
        public GetMarineWeatherResponse(ConsoleApp1.WheatherService.GetMarineWeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMarineWeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMarineWeatherResult;
        
        public GetMarineWeatherResponseBody() {
        }
        
        public GetMarineWeatherResponseBody(string GetMarineWeatherResult) {
            this.GetMarineWeatherResult = GetMarineWeatherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLuresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLures", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetLuresRequestBody Body;
        
        public GetLuresRequest() {
        }
        
        public GetLuresRequest(ConsoleApp1.WheatherService.GetLuresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLuresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BodyOfWater;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PredictTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Weather;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string WaterTemp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string WaterColor;
        
        public GetLuresRequestBody() {
        }
        
        public GetLuresRequestBody(string BodyOfWater, string PredictTime, string Weather, string WaterTemp, string WaterColor) {
            this.BodyOfWater = BodyOfWater;
            this.PredictTime = PredictTime;
            this.Weather = Weather;
            this.WaterTemp = WaterTemp;
            this.WaterColor = WaterColor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLuresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLuresResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetLuresResponseBody Body;
        
        public GetLuresResponse() {
        }
        
        public GetLuresResponse(ConsoleApp1.WheatherService.GetLuresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLuresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLuresResult;
        
        public GetLuresResponseBody() {
        }
        
        public GetLuresResponseBody(string GetLuresResult) {
            this.GetLuresResult = GetLuresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSSTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSST", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetSSTRequestBody Body;
        
        public GetSSTRequest() {
        }
        
        public GetSSTRequest(ConsoleApp1.WheatherService.GetSSTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSSTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _location;
        
        public GetSSTRequestBody() {
        }
        
        public GetSSTRequestBody(string _location) {
            this._location = _location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSSTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSSTResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetSSTResponseBody Body;
        
        public GetSSTResponse() {
        }
        
        public GetSSTResponse(ConsoleApp1.WheatherService.GetSSTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSSTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSSTResult;
        
        public GetSSTResponseBody() {
        }
        
        public GetSSTResponseBody(string GetSSTResult) {
            this.GetSSTResult = GetSSTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSSTChartsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSSTCharts", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetSSTChartsRequestBody Body;
        
        public GetSSTChartsRequest() {
        }
        
        public GetSSTChartsRequest(ConsoleApp1.WheatherService.GetSSTChartsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSSTChartsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _location;
        
        public GetSSTChartsRequestBody() {
        }
        
        public GetSSTChartsRequestBody(string _location) {
            this._location = _location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSSTChartsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSSTChartsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetSSTChartsResponseBody Body;
        
        public GetSSTChartsResponse() {
        }
        
        public GetSSTChartsResponse(ConsoleApp1.WheatherService.GetSSTChartsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSSTChartsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSSTChartsResult;
        
        public GetSSTChartsResponseBody() {
        }
        
        public GetSSTChartsResponseBody(string GetSSTChartsResult) {
            this.GetSSTChartsResult = GetSSTChartsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMoonPhaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMoonPhase", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetMoonPhaseRequestBody Body;
        
        public GetMoonPhaseRequest() {
        }
        
        public GetMoonPhaseRequest(ConsoleApp1.WheatherService.GetMoonPhaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMoonPhaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int year;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int month;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int day;
        
        public GetMoonPhaseRequestBody() {
        }
        
        public GetMoonPhaseRequestBody(int year, int month, int day) {
            this.year = year;
            this.month = month;
            this.day = day;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMoonPhaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMoonPhaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetMoonPhaseResponseBody Body;
        
        public GetMoonPhaseResponse() {
        }
        
        public GetMoonPhaseResponse(ConsoleApp1.WheatherService.GetMoonPhaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMoonPhaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMoonPhaseResult;
        
        public GetMoonPhaseResponseBody() {
        }
        
        public GetMoonPhaseResponseBody(string GetMoonPhaseResult) {
            this.GetMoonPhaseResult = GetMoonPhaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGamePredictionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGamePrediction", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetGamePredictionRequestBody Body;
        
        public GetGamePredictionRequest() {
        }
        
        public GetGamePredictionRequest(ConsoleApp1.WheatherService.GetGamePredictionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGamePredictionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sLocation;
        
        public GetGamePredictionRequestBody() {
        }
        
        public GetGamePredictionRequestBody(string sLocation) {
            this.sLocation = sLocation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGamePredictionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGamePredictionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.WheatherService.GetGamePredictionResponseBody Body;
        
        public GetGamePredictionResponse() {
        }
        
        public GetGamePredictionResponse(ConsoleApp1.WheatherService.GetGamePredictionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGamePredictionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGamePredictionResult;
        
        public GetGamePredictionResponseBody() {
        }
        
        public GetGamePredictionResponseBody(string GetGamePredictionResult) {
            this.GetGamePredictionResult = GetGamePredictionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeatherSoapChannel : ConsoleApp1.WheatherService.WeatherSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherSoapClient : System.ServiceModel.ClientBase<ConsoleApp1.WheatherService.WeatherSoap>, ConsoleApp1.WheatherService.WeatherSoap {
        
        public WeatherSoapClient() {
        }
        
        public WeatherSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.WheatherService.GetWeatherResponse ConsoleApp1.WheatherService.WeatherSoap.GetWeather(ConsoleApp1.WheatherService.GetWeatherRequest request) {
            return base.Channel.GetWeather(request);
        }
        
        public string GetWeather(string sLocation, string sLat, string sLong) {
            ConsoleApp1.WheatherService.GetWeatherRequest inValue = new ConsoleApp1.WheatherService.GetWeatherRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetWeatherRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sLat = sLat;
            inValue.Body.sLong = sLong;
            ConsoleApp1.WheatherService.GetWeatherResponse retVal = ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetWeather(inValue);
            return retVal.Body.GetWeatherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetWeatherResponse> ConsoleApp1.WheatherService.WeatherSoap.GetWeatherAsync(ConsoleApp1.WheatherService.GetWeatherRequest request) {
            return base.Channel.GetWeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetWeatherResponse> GetWeatherAsync(string sLocation, string sLat, string sLong) {
            ConsoleApp1.WheatherService.GetWeatherRequest inValue = new ConsoleApp1.WheatherService.GetWeatherRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetWeatherRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sLat = sLat;
            inValue.Body.sLong = sLong;
            return ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetWeatherAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.WheatherService.GetCurrentWeatherConditionsResponse ConsoleApp1.WheatherService.WeatherSoap.GetCurrentWeatherConditions(ConsoleApp1.WheatherService.GetCurrentWeatherConditionsRequest request) {
            return base.Channel.GetCurrentWeatherConditions(request);
        }
        
        public string GetCurrentWeatherConditions(string sLocation, string sLat, string sLong) {
            ConsoleApp1.WheatherService.GetCurrentWeatherConditionsRequest inValue = new ConsoleApp1.WheatherService.GetCurrentWeatherConditionsRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetCurrentWeatherConditionsRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sLat = sLat;
            inValue.Body.sLong = sLong;
            ConsoleApp1.WheatherService.GetCurrentWeatherConditionsResponse retVal = ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetCurrentWeatherConditions(inValue);
            return retVal.Body.GetCurrentWeatherConditionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetCurrentWeatherConditionsResponse> ConsoleApp1.WheatherService.WeatherSoap.GetCurrentWeatherConditionsAsync(ConsoleApp1.WheatherService.GetCurrentWeatherConditionsRequest request) {
            return base.Channel.GetCurrentWeatherConditionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetCurrentWeatherConditionsResponse> GetCurrentWeatherConditionsAsync(string sLocation, string sLat, string sLong) {
            ConsoleApp1.WheatherService.GetCurrentWeatherConditionsRequest inValue = new ConsoleApp1.WheatherService.GetCurrentWeatherConditionsRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetCurrentWeatherConditionsRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sLat = sLat;
            inValue.Body.sLong = sLong;
            return ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetCurrentWeatherConditionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempResponse ConsoleApp1.WheatherService.WeatherSoap.GetCurrentWeatherConditionsImageTemp(ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempRequest request) {
            return base.Channel.GetCurrentWeatherConditionsImageTemp(request);
        }
        
        public string GetCurrentWeatherConditionsImageTemp(string sLocation, string sLat, string sLong) {
            ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempRequest inValue = new ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sLat = sLat;
            inValue.Body.sLong = sLong;
            ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempResponse retVal = ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetCurrentWeatherConditionsImageTemp(inValue);
            return retVal.Body.GetCurrentWeatherConditionsImageTempResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempResponse> ConsoleApp1.WheatherService.WeatherSoap.GetCurrentWeatherConditionsImageTempAsync(ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempRequest request) {
            return base.Channel.GetCurrentWeatherConditionsImageTempAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempResponse> GetCurrentWeatherConditionsImageTempAsync(string sLocation, string sLat, string sLong) {
            ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempRequest inValue = new ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetCurrentWeatherConditionsImageTempRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sLat = sLat;
            inValue.Body.sLong = sLong;
            return ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetCurrentWeatherConditionsImageTempAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.WheatherService.GetTidesResponse ConsoleApp1.WheatherService.WeatherSoap.GetTides(ConsoleApp1.WheatherService.GetTidesRequest request) {
            return base.Channel.GetTides(request);
        }
        
        public string GetTides(string _location) {
            ConsoleApp1.WheatherService.GetTidesRequest inValue = new ConsoleApp1.WheatherService.GetTidesRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetTidesRequestBody();
            inValue.Body._location = _location;
            ConsoleApp1.WheatherService.GetTidesResponse retVal = ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetTides(inValue);
            return retVal.Body.GetTidesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetTidesResponse> ConsoleApp1.WheatherService.WeatherSoap.GetTidesAsync(ConsoleApp1.WheatherService.GetTidesRequest request) {
            return base.Channel.GetTidesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetTidesResponse> GetTidesAsync(string _location) {
            ConsoleApp1.WheatherService.GetTidesRequest inValue = new ConsoleApp1.WheatherService.GetTidesRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetTidesRequestBody();
            inValue.Body._location = _location;
            return ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetTidesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.WheatherService.GetMarineWeatherResponse ConsoleApp1.WheatherService.WeatherSoap.GetMarineWeather(ConsoleApp1.WheatherService.GetMarineWeatherRequest request) {
            return base.Channel.GetMarineWeather(request);
        }
        
        public string GetMarineWeather(string _location) {
            ConsoleApp1.WheatherService.GetMarineWeatherRequest inValue = new ConsoleApp1.WheatherService.GetMarineWeatherRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetMarineWeatherRequestBody();
            inValue.Body._location = _location;
            ConsoleApp1.WheatherService.GetMarineWeatherResponse retVal = ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetMarineWeather(inValue);
            return retVal.Body.GetMarineWeatherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetMarineWeatherResponse> ConsoleApp1.WheatherService.WeatherSoap.GetMarineWeatherAsync(ConsoleApp1.WheatherService.GetMarineWeatherRequest request) {
            return base.Channel.GetMarineWeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetMarineWeatherResponse> GetMarineWeatherAsync(string _location) {
            ConsoleApp1.WheatherService.GetMarineWeatherRequest inValue = new ConsoleApp1.WheatherService.GetMarineWeatherRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetMarineWeatherRequestBody();
            inValue.Body._location = _location;
            return ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetMarineWeatherAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.WheatherService.GetLuresResponse ConsoleApp1.WheatherService.WeatherSoap.GetLures(ConsoleApp1.WheatherService.GetLuresRequest request) {
            return base.Channel.GetLures(request);
        }
        
        public string GetLures(string BodyOfWater, string PredictTime, string Weather, string WaterTemp, string WaterColor) {
            ConsoleApp1.WheatherService.GetLuresRequest inValue = new ConsoleApp1.WheatherService.GetLuresRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetLuresRequestBody();
            inValue.Body.BodyOfWater = BodyOfWater;
            inValue.Body.PredictTime = PredictTime;
            inValue.Body.Weather = Weather;
            inValue.Body.WaterTemp = WaterTemp;
            inValue.Body.WaterColor = WaterColor;
            ConsoleApp1.WheatherService.GetLuresResponse retVal = ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetLures(inValue);
            return retVal.Body.GetLuresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetLuresResponse> ConsoleApp1.WheatherService.WeatherSoap.GetLuresAsync(ConsoleApp1.WheatherService.GetLuresRequest request) {
            return base.Channel.GetLuresAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetLuresResponse> GetLuresAsync(string BodyOfWater, string PredictTime, string Weather, string WaterTemp, string WaterColor) {
            ConsoleApp1.WheatherService.GetLuresRequest inValue = new ConsoleApp1.WheatherService.GetLuresRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetLuresRequestBody();
            inValue.Body.BodyOfWater = BodyOfWater;
            inValue.Body.PredictTime = PredictTime;
            inValue.Body.Weather = Weather;
            inValue.Body.WaterTemp = WaterTemp;
            inValue.Body.WaterColor = WaterColor;
            return ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetLuresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.WheatherService.GetSSTResponse ConsoleApp1.WheatherService.WeatherSoap.GetSST(ConsoleApp1.WheatherService.GetSSTRequest request) {
            return base.Channel.GetSST(request);
        }
        
        public string GetSST(string _location) {
            ConsoleApp1.WheatherService.GetSSTRequest inValue = new ConsoleApp1.WheatherService.GetSSTRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetSSTRequestBody();
            inValue.Body._location = _location;
            ConsoleApp1.WheatherService.GetSSTResponse retVal = ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetSST(inValue);
            return retVal.Body.GetSSTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetSSTResponse> ConsoleApp1.WheatherService.WeatherSoap.GetSSTAsync(ConsoleApp1.WheatherService.GetSSTRequest request) {
            return base.Channel.GetSSTAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetSSTResponse> GetSSTAsync(string _location) {
            ConsoleApp1.WheatherService.GetSSTRequest inValue = new ConsoleApp1.WheatherService.GetSSTRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetSSTRequestBody();
            inValue.Body._location = _location;
            return ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetSSTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.WheatherService.GetSSTChartsResponse ConsoleApp1.WheatherService.WeatherSoap.GetSSTCharts(ConsoleApp1.WheatherService.GetSSTChartsRequest request) {
            return base.Channel.GetSSTCharts(request);
        }
        
        public string GetSSTCharts(string _location) {
            ConsoleApp1.WheatherService.GetSSTChartsRequest inValue = new ConsoleApp1.WheatherService.GetSSTChartsRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetSSTChartsRequestBody();
            inValue.Body._location = _location;
            ConsoleApp1.WheatherService.GetSSTChartsResponse retVal = ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetSSTCharts(inValue);
            return retVal.Body.GetSSTChartsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetSSTChartsResponse> ConsoleApp1.WheatherService.WeatherSoap.GetSSTChartsAsync(ConsoleApp1.WheatherService.GetSSTChartsRequest request) {
            return base.Channel.GetSSTChartsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetSSTChartsResponse> GetSSTChartsAsync(string _location) {
            ConsoleApp1.WheatherService.GetSSTChartsRequest inValue = new ConsoleApp1.WheatherService.GetSSTChartsRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetSSTChartsRequestBody();
            inValue.Body._location = _location;
            return ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetSSTChartsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.WheatherService.GetMoonPhaseResponse ConsoleApp1.WheatherService.WeatherSoap.GetMoonPhase(ConsoleApp1.WheatherService.GetMoonPhaseRequest request) {
            return base.Channel.GetMoonPhase(request);
        }
        
        public string GetMoonPhase(int year, int month, int day) {
            ConsoleApp1.WheatherService.GetMoonPhaseRequest inValue = new ConsoleApp1.WheatherService.GetMoonPhaseRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetMoonPhaseRequestBody();
            inValue.Body.year = year;
            inValue.Body.month = month;
            inValue.Body.day = day;
            ConsoleApp1.WheatherService.GetMoonPhaseResponse retVal = ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetMoonPhase(inValue);
            return retVal.Body.GetMoonPhaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetMoonPhaseResponse> ConsoleApp1.WheatherService.WeatherSoap.GetMoonPhaseAsync(ConsoleApp1.WheatherService.GetMoonPhaseRequest request) {
            return base.Channel.GetMoonPhaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetMoonPhaseResponse> GetMoonPhaseAsync(int year, int month, int day) {
            ConsoleApp1.WheatherService.GetMoonPhaseRequest inValue = new ConsoleApp1.WheatherService.GetMoonPhaseRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetMoonPhaseRequestBody();
            inValue.Body.year = year;
            inValue.Body.month = month;
            inValue.Body.day = day;
            return ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetMoonPhaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.WheatherService.GetGamePredictionResponse ConsoleApp1.WheatherService.WeatherSoap.GetGamePrediction(ConsoleApp1.WheatherService.GetGamePredictionRequest request) {
            return base.Channel.GetGamePrediction(request);
        }
        
        public string GetGamePrediction(string sLocation) {
            ConsoleApp1.WheatherService.GetGamePredictionRequest inValue = new ConsoleApp1.WheatherService.GetGamePredictionRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetGamePredictionRequestBody();
            inValue.Body.sLocation = sLocation;
            ConsoleApp1.WheatherService.GetGamePredictionResponse retVal = ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetGamePrediction(inValue);
            return retVal.Body.GetGamePredictionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetGamePredictionResponse> ConsoleApp1.WheatherService.WeatherSoap.GetGamePredictionAsync(ConsoleApp1.WheatherService.GetGamePredictionRequest request) {
            return base.Channel.GetGamePredictionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.WheatherService.GetGamePredictionResponse> GetGamePredictionAsync(string sLocation) {
            ConsoleApp1.WheatherService.GetGamePredictionRequest inValue = new ConsoleApp1.WheatherService.GetGamePredictionRequest();
            inValue.Body = new ConsoleApp1.WheatherService.GetGamePredictionRequestBody();
            inValue.Body.sLocation = sLocation;
            return ((ConsoleApp1.WheatherService.WeatherSoap)(this)).GetGamePredictionAsync(inValue);
        }
    }
}
