//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPProject.Models.ImplJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int storeid { get; set; }
        public string storename { get; set; }
        public string city { get; set; }
        public string country { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
